name: test GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  set-secret:
    name: Set secret string
    runs-on: ubuntu-latest
    outputs:
      secret_string: ${{ steps.generate-string.outputs.secret_string }}
    steps:
      - name: Generate string
        id: generate-string
        run: |
          str="hogefugapiyo"
          echo "::add-mask::$str"
          echo "secret_string=$str" >> $GITHUB_OUTPUT
  check-secret:
    name: Check secret string
    runs-on: ubuntu-latest
    needs: set-secret
    steps:
      - name: Set Env
        run: |
          secret_str=${{ needs.set-secret.outputs.secret_string }}
          echo "SECRET_STRING=$secret_str" >> $GITHUB_ENV
      - name: Check Env
        run: echo $SECRET_STRING